version: '2'
services:
    vibe-app:
        image: vibe
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://vibe-postgresql:5432/vibe
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vibe-postgresql:
        extends:
            file: postgresql.yml
            service: vibe-postgresql
